# Stan Documentation

## Books {-}

We recommend working through this book using the textbooks Bayesian Data
Analysis, third edition (BDA3) and Statistical Rethinking: A Bayesian Course
with Examples in R and Stan as references on the concepts, and using the Stan
User's Guide and Reference Manual when necessary to clarify programming issues.
We discuss BDA in detail in a later chapter of this book.

## Stan manuals and guides {-}

The Stan documentation is at https://mc-stan.org/users/documentation/. 

* Stan User's Guide

The Stan user’s guide provides example models and programming techniques for
coding statistical models in Stan. It also serves as an example-driven
introduction to Bayesian modeling and inference.

Currently the User's Guide has Stan programs and code fragments, but no examples
that can be directly run from R or Python or the command line.


* Stan Language Reference Manual

The *Stan Reference Manual*
specifies the Stan programming language and inference algorithms.

* Stan Language Functions Reference

The
*Stan Functions Reference* specifies the functions built into the Stan
programming language.

* Documentation for interfaces

There is also a separate installation and getting started guide for
each of the Stan interfaces (R, Python, Julia, Stata, MATLAB, 
Mathematica, and command line).

Rstan:  https://mc-stan.org/rstan/

PyStan:  https://mc-stan.org/users/interfaces/pystan

CmdStan:  https://mc-stan.org/users/interfaces/cmdstan

## Web resources {-}

Stan is an open-source software project, resources for which are
hosted on various web sites:

* The [Stan Web Site](http://mc-stan.org/) organizes all of the resources
for the Stan project for users and developers.  It contains links to
the official Stan releases, source code, installation instructions,
and full documentation, including the latest version of this manual,
the user's guide and the getting started guide for each interface,
tutorials, case studies, and reference materials for developers.

* The [Stan Forums](http://discourse.mc-stan.org) provide structured
message boards for questions, discussion, and announcements related to
Stan for both users and developers.

* The [Stan GitHub Organization](https://github.com/stan-dev) hosts all
of Stan's code, documentation, wikis, and web site, as well as the
issue trackers for bug reports and feature requests and interactive
code review for pull requests.

## Example models {-}

The Stan case studies (https://mc-stan.org/users/documentation/case-studies) are
discussed in a later chaper of this book.  In addiiton, a large set of models
translated from BUGS, applied regression modeling examples, and examples from
other books here: https://github.com/stan-dev/example-models/wiki.

## Acknowledgements {-}

The Stan project could not exit without developers, users, and
funding.  Stan is a highly collaborative project.  The individual
contributions of the Stan developers to code is tracked through GitHub
and to the design conversation in the Wikis and forums.

Users have made extensive contributions to documentation in the way
of case studies, tutorials and even books.  They have also reported
numerous bugs in both the code and documentation.

Stan has been funded through grants for Stan and its developers,
through in-kind donations in the form of companies contributing
developer time to Stan and individuals contributing their own time to
Stan, and through donations to the open-source scientific software
non-profit NumFOCUS.  For details of direct funding for the project,
see the web site and project pages of the Stan developers.

